-- Update the default survey configuration with the actual survey data
UPDATE public.survey_configurations 
SET configuration = '{
  "title": "Leadership Sentiment, Adaptive and Agile Self-Assessment",
  "description": "This self-assessment is designed to help you explore your current leadership sentiment and intent, adaptability and agility. It will give insight into how you currently lead and respond to dynamic conditions, change, make decisions, empower others and lead in complexity.",
  "sections": [
    {
      "title": "Instructions",
      "type": "instructions",
      "content": "Leadership Sentiment, Purpose, Adaptive & Agility Self-Assessment (adapted from Joiner and Josephs)\n\nThis self-assessment is designed to help you explore your current leadership sentiment and intent, adaptability and agility.\n\nIt will give insight into how you currently lead and respond to dynamic conditions, change, make decisions, empower others and lead in complexity.\n\nWhy Combine Sentiment, Intent and Leadership Agility?\n\nMost leadership assessments focus only on what leaders do - behaviours, styles, or competencies. But leadership isn''t just behavioural. It''s also deeply emotional, situational, and purpose driven.\n\nBy combining how leaders feel (sentiment), how they lead (adaptive agility), and why they lead (intent and purpose), we''ll unlock a far more complete picture of your leadership.\n\nWe''ll ask questions about your current capabilities, motivation, mindset, and direction - the internal drivers that influence how you show up, adapt, and grow over time as a leader.\n\nThis three-part survey creates a richer starting point for personal development, coaching, and programme impact.\n\nIt allows you to move from self-awareness to purposeful action - aligned with who you are and the kind of leader you want to become.\n\nThis pre-assessment in advance of your LEADForward program, is designed to help you reflect on how you lead today, how you''re feeling in your leadership role, and where you want to go next. It combines:\n\n• How you feel and experience leadership (Sentiment)\n• What drives you and where you''re headed (Purpose)  \n• How you show up and adapt in complexity (Agility)\n\nTogether, these insights provide a richer, more complete picture of your leadership - one that''s both practical and personal and can be used to help shape your leadership journey.\n\nHow This Helps:\n\n• At the start of the programme, this provides you an understanding of your leadership that will help both within LEADForward as well as within your coaching sessions.\n\n• This self-assessment survey will be repeated at the end of the LEADForward program and will help show shifts in your mindset, thinking, perspectives and capabilities.\n\n• This self-assessment is to give you a point in time perspective, there are no right wrong answers and is purely to give you a sense of where you are currently at.\n\nInstructions:\nBefore you complete the full self-assessment, take the opportunity to complete this in a quiet and calm space so that you can fully reflect.\n\nPlease answer these questions honestly. There are no right or wrong answers. Your responses will help you build insights and understanding as well as track shifts in mindset and perspective over time.\n\nYour facilitator and coach will have oversight into your responses as this will help inform our leadership and coaching sessions. Your personal responses will not be shared more broadly."
    }
  ]
}'::jsonb
WHERE survey_type = 'leadership_assessment' AND is_active = true;